export default {
  $schema: "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  _comment: "This config was generated by the CivicFlow automation",
  testRunner: "vitest",
  reporters: ["html", "clear-text", "progress"],
  coverageAnalysis: "perTest",
  mutate: [
    "src/**/*.ts?(x)",
    "!src/**/*.test.ts?(x)",
    "!src/app/layout.tsx",
  ],
};
